### ISSUE TITLE
Seasons 11+ not sorted

### ISSUE THREAD

**Issue by bverc** [alombarte/raspberry-osmc-automated#26]
Apologies if this only affects me, or my code is out of date, but I notice that the latest season of The Big Bang Theory downloads fine, but fails to move from Downloads folder. I wonder if there is some cap stopping episodes from seasons 11 and higher from moving.

**Comment by alombarte** [comment]
Hi Brendan,

Can you provide the output log when you run flexget?

On 10 Oct 2017 10:13, "Brendan Vercoelen" <notifications@github.com> wrote:

Apologies if this only affects me, or my code is out of date, but I notice
that the latest season of The Big Bang Theory downloads fine, but fails to
move from Downloads folder. I wonder if there is some cap stopping episodes
from seasons 11 and higher from moving.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alombarte/raspberry-osmc-automated/issues/26>, or mute
the thread
